const arr = [{cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"},
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"},
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"},
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}, 
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}, 
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}, 
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}, 
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}, 
    {cloth : "T-Shirt" ,offer : "20-30%"}, 
    {cloth : "Shirt" ,offer : "20-30%"},
    {cloth : "Pants" ,offer : "20-30%"}]

export default arr